language: bash

deploy:
  provider: s3
  access_key_id: AKIAIY4RILRJUD5FSKHQ
  secret_access_key:
    secure: Oe6jVLHfYwdqMeFu2nqMhxvlLgTd345liyottT3C4ROeeL/e67hbYul75f/2FT8/vrILsClu9F24uBTr2O8i0ZilFztVGspVh5Al8oXQ62tlkC4WG/vEWPsUm+/3RJkoTaXyjB0yBSxot0dJs8ADv9aYnMiVOZSZCCA/4fCL3iw=
  bucket: lang-jvm
  local-dir: builds
  upload-dir: sbt/stage
  acl: !ruby/string:HighLine::String |-
    cHVibGljX3JlYWQ=
  on:
    repo: heroku/sbt-pkg-builder

script: ./bin/build-play23.sh
