language: bash
script: "./bin/build-play23.sh"
deploy:
  provider: codedeploy
  access_key_id: AKIAIY4RILRJUD5FSKHQ
  secret_access_key:
    secure: FQ0eOr+HRv72aHyKpblEvJhSdNBtvyXWLFppnpT3i8SGIMVxBALohQeXonEQzncy79HzaF8H9ycBD8vmPg5DAnzFYmE/zURaVclyS6uGP5n+28H4HNucTtf9VnxiJ1WYOzpyy1bC64Q3oQ5/2Dc0FXSNKOo0oXZYxQEpIwhojCc=
  bucket: lang-jvm
  application: sbt-pkg-builder
  skip_cleanup: true
  local-dir: builds
  upload-dir: sbt/stage
  acl: public_read
  on:
    repo: heroku/sbt-pkg-builder
