language: bash
script: "./bin/build-play23.sh"
deploy:
  provider: s3
  access_key_id: AKIAIY4RILRJUD5FSKHQ
  secret_access_key:
    secure: AMTiEGB6Gtn/Gu3Vk3p4q1ZXuyTrnhHWfRNvx5vdsBDa7CXN6OiRcNnjGFfxOGBa0hpDq3cr/cHiBhsUb6BeBI7Uyx9NI2PFhqbtGwJlh4k/R2ONYsdQgvIEfcMU4gJK4ESbX3iVJWcHJO+w4bZ3atmDKk/VIyqm89E6GtgT74g=
  bucket: lang-jvm
  local-dir: builds
  acl: bucket_owner_full_control
  on:
    repo: heroku/sbt-pkg-builder
